name: Flutter CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  flutter:
    name: Flutter Lint & Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check Version Consistency
        run: ./tool/check_versions.sh

      - name: Install Dependencies
        run: flutter pub get

      - name: Format Check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Project Source
        run: flutter analyze

      - name: Run Tests
        run: flutter test
